spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web
lotto:
  number-generator:
    facade:
      count: 25
      lowerBand: 1
      upperBand: 99
    http:
      client:
        config:
          uri:
          port: 9090
          connectionTimeout: 5000
          readTimeout: 5000